theme = "space-villain"
icons = "awesome"


[[block]]
block = "music"
player = "rhythmbox"
buttons = ["prev", "play", "next"]
seek_step = 30000

[[block]]
block = "uptime"

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
# clickable = true
# warning_mem = 65
# critical_mem = 80

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "wlx107b4455c4b7"
format = "{ssid} {signal_strength} {ip} {speed_up;K*b} {speed_down;K*b}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "keyboard_layout"
driver = "xkbswitch"
on_click = "xkb-switch -n"
format = "{layout} {variant}"
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "custom"
command = "whoami"
interval = "once"
